version: '2.1'

services:

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_TAG}
    container_name: elasticsearch
    environment:
      - cluster.name=${CLUSTER_NAME}
      - node.name=${NODE_NAME}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${HEAP_SIZE} -Xmx${HEAP_SIZE}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: ${ELASTIC_MEM_LIMIT}
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:${ELASTIC_DATA}
      - ./elasticsearch/config:/usr/share/elasticsearch/config
    ports:
      - "${ELK_BIND_IP}:9200:9200"
    healthcheck:
        test: curl -fs http://localhost:9200/
    networks:
      - ${NET_NAME}
  
  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_TAG}
    container_name: kibana
    mem_limit: ${KIBANA_MEM_LIMIT}
    volumes:
      - ./kibana/config:/opt/kibana/config
    ports:
      - "${ELK_BIND_IP}:5601:5601"
    healthcheck:
        test: curl -fs http://localhost:5601/
    networks:
      - ${NET_NAME}
    depends_on:
        elasticsearch:
            condition: service_healthy

  # SpamScope
  spamscope:
    image: ${SPAMSCOPE_IMAGE_NAME}
    #build: .
    container_name: spamscope
    mem_limit: ${SPAMSCOPE_MEM_LIMIT}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${SPAMSCOPE_BIND_IP}:8080:8080"
    volumes:
      - ${HOST_SPAMSCOPE_CONF}:/etc/spamscope
      - ${HOST_MAILS_FOLDER}:${DOCKER_MAILS_FOLDER}
    healthcheck:
        test: curl -fs http://localhost:8080/
    networks:
      - ${NET_NAME}
    depends_on:
        elasticsearch:
            condition: service_healthy

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge
